### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Skeli789** [ipatix/gba-hq-mixer#5]
## Environment
Visual Boy Advance-M 2.1.1

## Details
I tested this thoroughly using both the old sound engine (2.1) and the current engine (4.0). The following crash only happens with v4.0 both with and without the changes suggested [here](https://github.com/ipatix/gba-hq-mixer/issues/4) (the following video example is using the original code in the repo).

https://user-images.githubusercontent.com/17243618/119367621-22c36a80-bc80-11eb-8c2c-f10d19a1bc87.mp4

The disassembler shows an infinite increase now:

![image](https://user-images.githubusercontent.com/17243618/119367105-a03aab00-bc7f-11eb-8af5-673d106fb186.png)

## Additional Details
If it helps, the ``hq_buffer_ptr`` constant was set to ``0x30028E0``.

**Comment by ipatix** [comment]
This occurs due to corruption of DMA registers.

If you do binary hacking, change ENABLE_DMA to 0. If you do decomp modding, make the DMA transfers atomic. Check this for instructions on how to do it: https://github.com/pret/pokeemerald/wiki/Implementing-ipatix%27s-High-Quality-Audio-Mixer
