### ISSUE TITLE
R0/R6 issue?

### ISSUE THREAD

**Issue by easyaspi314** [ipatix/gba-hq-mixer#8]
I was trying to document the code (and convert to unified syntax so it can compile with Clang's built-in assembler), and noticed this:
https://github.com/ipatix/gba-hq-mixer/blob/main/m4a_hq_mixer.s#L890-910
L891 and L900 both refer to `R6` in the comment, but actually operate on `R0`. It seems like the rest of the code expects it to be in `R6` like the comment.

**Comment by ipatix** [comment]
If my memory serves me well, I don't know why R6 would make any sense there. I'll correct it.

**Comment by ipatix** [comment]
Huh, I thought I already fixed this... Apparently I forgot
